<?php

namespace App\Controller;

use Cake\Datasource\ConnectionManager;
use Cake\Error\Debugger;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class ExemplosModelController extends AppController {

	/*
	 *  CAKEPHP suporta esses bancos
	 *
	 * MySQL 5.1+
	 * SQLite 3
	 * PostgreSQL 8+
	 * SQLServer 2008+
	 * Oracle (through a community plugin)
	 */
	public function beforeFilter(Event $event) {
		parent::beforeFilter($event); // TODO: Change the autogenerated stub

		$this->loadModel("Produtos");
	}

	//busca simples
	public function index() {

		$categorias = TableRegistry::get('Categorias');

		$query = $categorias->find();

		foreach ($query as $row) {
			Debugger::dump($row->nome);
		}

	}

	// podemos escrever o sql puro, ou entao, utilizar a classe builder de SQL, como abaixo.
	public function construindoSQL() {

		//pegamos a configuraçao padrao do framework
		$conexao = ConnectionManager::get('default');
		$resultados = $conexao->newQuery()->select('*')->from('categorias')->where(['id >' => 2])->execute()->fetchAll('assoc');

		Debugger::dump($resultados);

		foreach ($resultados as $row) {
			Debugger::dump($row['nome']);
		}
		$this->render("index");
	}

	public function buscandoDados() {

		$categorias = TableRegistry::get('Categorias');

		$categoria = $categorias->get(1);
		Debugger::dump($categoria);

		$categoria = $categorias->find('all');
		Debugger::dump($categoria);

		$this->render('index');
	}

	public function comoFunciona() {
		// Find all the produtos.
		// At this point the query has not run.
		$produtos = TableRegistry::get('Produtos');
		$query = $produtos->find('all');

		Debugger::dump("TESTE 1");
		Debugger::dump($query);

		// Iteration will execute the query.
		Debugger::dump("TESTE 2");
		foreach ($query as $row) {
			Debugger::dump($row);
		}

		// Calling all() will execute the query
		// and return the result set.
		Debugger::dump("TESTE 3");
		$results = $query->all();
		Debugger::dump($results);

		// Once we have a result set we can get all the rows
		Debugger::dump("TESTE 4");
		$data = $results->toArray();
		Debugger::dump($data);

		// Converting the query to an array will execute it.
		Debugger::dump("TESTE 5");
		$results = $query->toArray();
		Debugger::dump($results);

		$this->render('index');
	}


	public function exemploDisplayField() {

		$produtos = TableRegistry::get('Produtos');
		$query = $produtos->find('list');

		$resultados = $query->toArray();
		Debugger::dump($resultados);

		$query = $produtos->find('list', [
			'keyField' => 'slug',
			'valueField' => 'nome'
		]);

		$resultados = $query->toArray();
		Debugger::dump($resultados);


		$query = $produtos->find('list', [
			'keyField' => 'slug',
			'valueField' => 'nome',
			'groupField' => 'categoria_id'
		]);

		$resultados = $query->toArray();
		Debugger::dump($resultados);

		// ativar o display field no model!
		$this->render("index");

	}


	public function metodosMagicos() {
		// The following two calls are equal.
		$query = $this->Produtos->findByNome('Barbie');
		$resultados = $query->toArray();
		Debugger::dump($resultados);

		$query = $this->Produtos->findAllByCategoriaId(1);
		$resultados = $query->toArray();
		Debugger::dump($resultados);

		// Se for usar em uma table tem que usar como no exemplo abaixo
		//$produtos = TableRegistry::get('Produtos');

		//$query = $produtos->findByUsername('joebob');
		//$query = $produtos->findAllByUsername('joebob');

		$this->render("index");
	}

	public function camposVirtuais() {

		$query = $this->Produtos->find('all');

		foreach ($query as $row) {
			Debugger::dump($row->slug_nome);
		}

		$this->render('index');
	}

}